{
  "comment": "Exported from https://atlas.bot",
  "formatVersion": 2,
  "exportedAt": "2023-01-27T12:25:45.946Z",
  "actions": [
    {
      "id": "665efaf5-861c-4fa1-8fc3-d27913ca8774",
      "flags": 0,
      "name": "My Action",
      "trigger": {
        "type": 0,
        "name": "join",
        "channelId": null,
        "description": "Allows you to join the event ",
        "parameters": []
      },
      "disabled": false,
      "content": "Hello {user.mention}!\r\n{void;\r\n\r\n{=array;{store.get;globalUserArray}}\r\n\r\n\r\n[#for;{=item};{$array}]\r\n\r\n{if;{user.id};==;{$item.user};{return;You are already participating!}}\r\n// checks if user is already participating\r\n[/for]\r\n\r\n{push ;{$array};{{\"user\": \"{user.id;}\", \"xp\": \"{user.xp;}\"}}}\r\n} // end of void\r\nYou have joined the event!\r\n{store.set;globalUserArray;{$array}}",
      "restriction": {
        "permissions": "0",
        "role": {
          "mode": 1,
          "value": [
            "266694172654698496"
          ]
        },
        "channel": {
          "mode": 0,
          "value": []
        }
      },
      "cooldownSeconds": 0,
      "createdAt": "2023-01-25T19:50:01.285Z",
      "updatedAt": "2023-01-27T09:48:20.616Z",
      "task": null
    }
  ]
}